<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZucchiUser\Module'                     => __DIR__ . '//Module.php',
    'ZucchiSecurity\Event\UserEvent'        => __DIR__ . '//src/ZucchiUser/Event/UserEvent.php',
    'ZucchiUser\Event\UserListener'         => __DIR__ . '//src/ZucchiUser/Event/UserListener.php',
    'ZucchiUser\Entity\User'                => __DIR__ . '//src/ZucchiUser/Entity/User.php',
    'ZucchiUser\Entity\Event'               => __DIR__ . '//src/ZucchiUser/Entity/Event.php',
    'ZucchiUser\Controller\AdminController' => __DIR__ . '//src/ZucchiUser/Controller/AdminController.php',
    'ZucchiUser\Service\User'               => __DIR__ . '//src/ZucchiUser/Service/User.php',
);